version: "3.9"
services:
  app:
    image: "${DOCKERHUB_USER}/${APP_NAME}:${APP_TAG}"
    container_name: "${APP_NAME}"
    ports:
      - "${APP_PORT:-8080}:8080"
    env_file:
      - .env
    restart: unless-stopped

