spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/diary_backend
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

crawler:
  kca:
    baseUrl: "https://counselors.or.kr"
    listPath: "/KOR/license/supervisor_6.php"
    timeoutMs: 8000
    minDelayMs: 800
    maxDelayMs: 1500
    maxPages: 200
    userAgent: "MindNoteCrawler/1.0 (+https://your-service.example) Mozilla/5.0"

  jwt:
    secret: ${JWT_SECRET}

aws:
  s3:
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    bucketName: ${AWS_S3_BUCKET_NAME}


logging:
  level:
    root: INFO
    com.example.crawler.kca: DEBUG   # 우리 크롤러 패키지 상세 로그
