spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

crawler:
  kca:
    baseUrl: "https://counselors.or.kr"
    listPath: "/KOR/license/supervisor_6.php"
    timeoutMs: 8000
    minDelayMs: 800
    maxDelayMs: 1500
    maxPages: 200
    userAgent: "MindNoteCrawler/1.0 (+https://your-service.example) Mozilla/5.0"


  jwt:
    secret: ${JWT_SECRET}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-url: ${KAKAO_REDIRECT_URL}

toss:
  payments:
    client-key: ${TOSS_CLIENT_KEY}
    secret-key: ${TOSS_SECRET_KEY}
    success-url: ${TOSS_SUCCESS_URL}
    fail-url: ${TOSS_FAIL_URL}

logging:
  level:
    root: INFO
    backend.crawler.kca: DEBUG
